# Generated by Django 5.2.2 on 2025-06-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Science Fiction'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('animation', 'Animation'), ('documentary', 'Documentary'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery')], max_length=50, null=True)),
                ('language', models.CharField(blank=True, choices=[('english', 'English'), ('bengali', 'Bengali'), ('hindi', 'Hindi'), ('odia', 'Odia'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam'), ('punjabi', 'Punjabi')], max_length=50, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('duration_minuts', models.PositiveIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
    ]
